import Head from 'next/head'
import {Box,Tabs, TabList, TabPanels, Tab, TabPanel} from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
          <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Box backgroundColor="primary.900">Homew</Box>
      <Tabs  variant='enclosed'>
        <TabList>
          <Tab>One</Tab>
          <Tab>Two</Tab>
          <Tab>Three</Tab>
        </TabList>

        <TabPanels>
          <TabPanel>
            <p>one!</p>
          </TabPanel>
          <TabPanel>
            <p>two!</p>
          </TabPanel>
          <TabPanel>
            <p>three!</p>
          </TabPanel>
        </TabPanels>
      </Tabs>
    </div>
  )
}
